### ISSUE TITLE
Tip: Visual Studio packages ondersteunen nu layout directory

### ISSUE THREAD

**Issue by riezebosch** [kc/images#1]
https://github.com/jberezanski/ChocolateyPackages/issues/17#issuecomment-334877324

Voor offline installatie waar ik destijds een eigen package voor heb gebakken.

**Comment by catsburg** [comment]
@riezebosch Dank voor de tip! Ik had dit ook al gezien inderdaad. Enige tijd geleden heb ik dit ook al aangepast. In de nieuwe boxstarter package voor vs2017 o.b.v. winsrv2016 wordt hiervan gebruik gemaakt (en dus niet meer van jouw custom offline installation package). Het nieuwe boxstarter package script is embedded in de git repo's op de file share(s) voor TDS. Er wordt hiervoor dus geen gebruik meer gemaakt van deze repo op GitHub. Het script voor de vs2017 package hier op GitHub wordt alleen nog gebruikt in de oude(re) TDS template(s).
